W6D5/cat_project/config/routes.rb
Rails.application.routes.draw do
  get 'cat_rental_requests/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:index, :show, :create, :new, :edit, :update]

  resources :cat_rental_requests, only: [:new, :create, :edit]
end

W6D5/cat_project/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null

require 'action_view'

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  CAT_COLORS = ['Orange', 'White', 'Black', 'Gray']

  validates :birth_date, :name, presence: true
  validates :color, presence: true, inclusion: CAT_COLORS
  validates :sex, presence: true, inclusion: {in: ['M', 'F']}

  has_many :rental_requests,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: 'CatRentalRequest',
    dependent: :destroy

   def age
    time_ago_in_words(birth_date)
  end
end

W6D5/cat_project/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint           not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class CatRentalRequest < ApplicationRecord
  STATUS = ['PENDING', 'APPROVED', 'DENIED']

  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, inclusion: STATUS
  # validates :overlapping_requests

  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: 'Cat'

  def overlapping_requests 

  end

  def overlapping_approved_requests

  end

  def does_not_overlap_approved_request
    
  end
end

W6D5/cat_project/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @rental_request = CatRentalRequest.new
    render :new
  end

  def create 
    @rental_request = CatRentalRequest.new(rental_params)

    if @rental_request.save 
      redirect_to cat_url(@rental_request.cat)
    else
      flash.now[:errors] = @rental_request.errors.full_messages 
      render :new
    end
  end

  private 

  def rental_params 
    params.require(:cat_rental_request).permit(:cat_id, :end_date, :start_date, :status)
  end
end

W6D5/cat_project/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all 
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id]) 
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create 
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cats_url
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update 
    @cat = Cat.find_by(id: params[:id])

    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else  
      flash.now[:errors] = @cat.errors.full_messages
      render :edit 
    end
  end

  private 

  def cat_params
    params.require(:cat).permit(:name, :color, :sex, :description, :birth_date)
  end
end

W6D5/cat_project/app/views/cat_rental_requests/new.html.erb
<h1>Rental Request</h1>

<form action="<%= new_cat_rental_request_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <label for="cat_id">Cat</label>
  <select name="cat_rental_request[cat_id]" id="cat_id">
    <option selected>--Pick a cat--</option>
    <% Cat.all.each do |cat| %>
      <option value="<%= cat.id %>" <%= @rental_request.id == cat.id ? "selected" : "" %>><%= cat.name %></option>
    <% end %>
  </select>

  <br>

  <label for="start_date">Start Date</label>
  <input type="date" name="rental_request[start_date]" id="start_date" value="<%= @rental_request.start_date %>">

  <br> 
  
  <label for="end_date">End Date</label>
  <input type="date" name="rental_request[end_date]" id="end_date" value="<%= @rental_request.end_date %>">

  <br>
  <input type="submit" value="Submit">
</form>

W6D5/cat_project/app/views/cats/_form.html.erb
<% action = cat.persisted? ? cat_url(cat) : cats_url %>
<% method = cat.persisted? ? :patch : :post %>

<form action="<%= action %>" method="POST">
  <input type="hidden" name="_method" value="<%= method %>" >
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="cat_name">Name</label>
  <input type="text" name="cat[name]" id="cat_name" value="<%= cat.name %>">

  <br> 
  
  <input type="radio" name="cat[sex]" id="cat_sex_male" value="M" <%= cat.sex == "M" ? "checked" : "" %>>
  <label for="cat_sex_male">Male</label>
  <input type="radio" name="cat[sex]" id="cat_sex_female" value="F" <%= cat.sex == "F" ? "checked" : "" %>>
  <label for="cat_sex_female">Female</label>

 <br><br>

  <label for="cat_color">Color</label>
  <select name="cat[color]" id="cat_color">
    <option selected>--select a color--</option>
      <% Cat::CAT_COLORS.each do |color| %>
      <option value="<%= color %>" <%= cat.color == color ? "selected" : "" %>><%= color %></option>
    <% end %>
  </select>

 <br>

  <label for="cat_birth_date">Birth Date</label>
  <input type="date" name="cat[birth_date]" id="cat_birth_date" value="<%= cat.birth_date %>">

  <br>

  <label for="cat_description">Description</label>
  <textarea name="cat[descirption]" id="cat_description"><%= cat.description %></textarea>
 

  <input type="submit" value="Submit">
</form>

W6D5/cat_project/app/views/cats/edit.html.erb
<h1>Edit Cat</h1>

<h2><%= @cat.name %></h2>

<%= render 'form', cat: @cat %>

W6D5/cat_project/app/views/cats/index.html.erb
<h1>All Cats</h1>

<div class="list-cats">
  <% @cats.each do |cat| %>
    <li>
      <a href="<%= cat_url(cat.id) %>" class="list-cat-item"><%= cat.name %></a>
    </li>
  <% end %>
</div>

W6D5/cat_project/app/views/cats/new.html.erb
<h1>Add New Cat</h1>

<%= render 'form', cat: @cat %>

W6D5/cat_project/app/views/cats/show.html.erb
<%= @cat.name %>

<table>
  <thead>
    <tr>
      <th>ATTRIBUTE</th>
      <th>VALUE</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>AGE</td>
      <td><%= @cat.age %></td>      
    </tr>
      <td>BIRTH_DATE</td>
      <td><%= @cat.birth_date %></td>
    <tr>
      <td>COLOR</td>
      <td><%= @cat.color %></td>
    </tr>
    <tr>
      <td>SEX</td>
      <td><%= @cat.sex %></td>
    </tr>
    
    <% if @cat.description %>
      <tr colspan="2">
        <td><%= @cat.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

W6D5/cat_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:errors] %>
      <%= flash[:errors].join(", ") %>
    <% end %>
    <%= yield %>
  </body>
</html>